[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
gateway_vault = "6iKSqqM82HpiNP7VzLNfEppqzfLPFAhY2DWmz7gmQQTs"

[programs.mainnet]
gateway_vault = "6iKSqqM82HpiNP7VzLNfEppqzfLPFAhY2DWmz7gmQQTs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/wagmi-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
